name: Java CI

on:
  push:
    branches: [development-books-kata]
  pull_request:
    branches: [development-books-kata]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build and run tests with Maven
        run: mvn -B clean test
